spring.application.name=Nulances

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/nulances
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=false
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=false

spring.jackson.time-zone=America/Sao_Paulo

logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.flywaydb=INFO

app.jwt.secret=V3JvQ1hFQ2ZpV2R4YjZzU3ZkRk5oQk9Yc3p0a1VnT2h4bU1uWk1ZVnV4c1pZcW5JbEJ2Z1hYd0dRZ2tYV3lJc2F1cG9tRk5qQ2x1R0RjZ0FzZlF3b0Z2Y1pUeA==
app.jwt.expiration=900000

resend.api-key=re_Yq4bkvy3_MPgotwPPQBQgGnMGzpP83dW8
resend.from.email=contato@nulances.com
resend.from.name=NuLances
app.frontend.url=http://localhost:3000

app.email.confirmacao.expiracao-minutos=15
app.jms.queue-email-confirmacao=email.confirmacao.queue
app.jms.queue-lance-recebido=queue.lance.recebido
app.jms.queue-cobranca-plano=queue.cobranca.plano
app.jms.queue-arrematacao-vencedor=queue.arrematacao.vencedor

spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=admin
spring.activemq.password=admin
spring.jms.pub-sub-domain=false

# Mercado Pago (preencher com seus dados)
app.payment.mercadopago.api-base-url=https://api.mercadopago.com
app.payment.mercadopago.access-token=APP_USR-7636544080949958-042211-75dad78ecb1a8bb91ead773c4a93d329-1248914660
app.payment.mercadopago.public-key=APP_USR-94c88257-fb26-4a03-af35-be60e5fa5dc8
app.payment.mercadopago.webhook-secret=df58f48875b7355d5dea26ba2f5cf6eb0bbd8d5eb4fdeb1efb5bde14345b3d7e
app.payment.mercadopago.webhook-url=https://nulances-backend-production-509c.up.railway.app/payment/webhook/mercadopago
app.payment.mercadopago.success-url=https://www.nulances.com/vendedor/planos/sucesso
app.payment.mercadopago.pending-url=https://www.nulances.com/vendedor/planos/pendente
app.payment.mercadopago.failure-url=https://www.nulances.com/vendedor/planos/falha

# Cobrança recorrente de planos
app.payment.assinatura.dias-vigencia=30
app.payment.assinatura.dias-tolerancia-inadimplencia=3

app.r2.account-id=d64704964e2a94abe48a454c5949cb34
app.r2.access-key=c919d70833cb3cdf1974234de954884c
app.r2.secret-key=c4ef393b82d766842fecc3824d76cbec0333bb5bf1b4bbfd986c977be232b707
app.r2.bucket=nulances
app.r2.upload-expires-in-seconds=900
app.r2.download-expires-in-seconds=900