package com.Nulances.domain.enums;

public enum CategoriaAnuncio {
    VEICULOS,
    IMOVEIS,
    CELULARES_E_TELEFONIA,
    CASA_DECORACAO_E_UTENSILIOS,
    ESPORTES_E_FITNESS,
    SERVICOS,
    MODA_E_BELEZA,
    ARTIGOS_INFANTIS,
    ANIMAIS_DE_ESTIMACAO,
    MUSICA_E_HOBBIES,
    AGRO_E_INDUSTRIA,
    MAQUINAS,
    VAGAS_DE_EMPREGO,
    COMERCIO,
    GAMES,
    TVS_E_VIDEO,
    AUDIO,
    INFORMATICA,
    ELETRO,
    MOVEIS,
    MATERIAIS_DE_CONSTRUCAO,
    ESCRITORIO_E_HOME_OFFICE
}
